[package]
name = "lorawan"
version = "0.1.0"
authors = ["Marc Nijdam <marc_@helium.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
byteorder = "1.3"
bitfield = "0.13"
rand = "0.8.5"

[dev-dependencies]
base64 = "0"
